### ISSUE TITLE
Do you plan an Magento 2.0 Version of Order Reminders?

### ISSUE THREAD

**Issue by Drifti** [Kinento/order-reminders#6]

**Comment by CNugteren** [comment]
Sorry, but I am no longer developing this extension:
> From 2009 until 2014, Kinento has sold the Magento Order Reminders module for 79 euro per license. From 2015 onwards, updates are no longer provided by Kinento, but the module is instead available on GitHub free of charge. The code is released under the MIT open-source license and community patches and feature additions are encouraged.

You'll have to rely on the community or see if someone else picks it up.
